In [1]:
# Lab Setup: create sample CSV, Excel, and JSON files
import pandas as pd

# customers.csv
customers = pd.DataFrame([
    {"customer_id": 1, "name": "Asha Kapoor", "city": "Pune", "loyalty_points": 120},
    {"customer_id": 2, "name": "Rahul Mehta", "city": "Mumbai", "loyalty_points": 80},
    {"customer_id": 3, "name": "Sita Rao", "city": "Bengaluru", "loyalty_points": None},
    {"customer_id": 4, "name": "John Doe", "city": "Pune", "loyalty_points": 200},
    {"customer_id": 5, "name": "Priya Singh", "city": None, "loyalty_points": 50},
])
customers.to_csv("customers.csv", index=False)

# orders.csv
orders = pd.DataFrame([
    {"order_id": 101, "customer_id": 1, "product": "Keyboard", "amount": 1200.0, "order_date": "2024-05-01"},
    {"order_id": 102, "customer_id": 2, "product": "Mouse", "amount": 350.5, "order_date": "2024-05-02"},
    {"order_id": 103, "customer_id": 1, "product": "Monitor", "amount": 8000.0, "order_date": "2024-05-02"},
    {"order_id": 104, "customer_id": 3, "product": "Laptop", "amount": 55000.0, "order_date": "2024-05-03"},
    {"order_id": 105, "customer_id": 2, "product": "Webcam", "amount": 1500.0, "order_date": "2024-05-04"},
    {"order_id": 106, "customer_id": 5, "product": "Headset", "amount": 900.0, "order_date": "2024-05-05"},
])
orders.to_csv("orders.csv", index=False)

# products.json
products = [
    {"product_id": "P01", "product_name": "Keyboard", "category": "Accessories"},
    {"product_id": "P02", "product_name": "Mouse", "category": "Accessories"},
    {"product_id": "P03", "product_name": "Monitor", "category": "Displays"},
]
import json
with open("products.json", "w") as f:
    json.dump(products, f, indent=2)

# Save an Excel file (orders with additional sheet)
with pd.ExcelWriter("orders.xlsx") as writer:
    orders.to_excel(writer, sheet_name="orders", index=False)
    customers.to_excel(writer, sheet_name="customers", index=False)

# Lab 1: Series vs DataFrame

In [2]:
customers = pd.read_csv("customers.csv")
print(customers["loyalty_points"])

print(type(customers), customers.shape)

0    120.0
1     80.0
2      NaN
3    200.0
4     50.0
Name: loyalty_points, dtype: float64
<class 'pandas.core.frame.DataFrame'> (5, 4)

# Lab 2: Create DataFrame from dictionary

In [5]:
products = [
    {"product_id":"P10", "product_name": "USB Cable", "price":250.0},
    {"product_id":"P11", "product_name": "Charger", "price":799.0},
    {"product_id":"P12", "product_name": "Power Bank", "price":1299.5}
    ]
pd.DataFrame(products)

  product_id product_name   price
0        P10    USB Cable   250.0
1        P11      Charger   799.0
2        P12   Power Bank  1299.5

# Lab 3: Read CSV file

In [7]:
orders  =  pd.read_csv("orders.csv")
orders

   order_id  customer_id   product   amount  order_date
0       101            1  Keyboard   1200.0  2024-05-01
1       102            2     Mouse    350.5  2024-05-02
2       103            1   Monitor   8000.0  2024-05-02
3       104            3    Laptop  55000.0  2024-05-03
4       105            2    Webcam   1500.0  2024-05-04
5       106            5   Headset    900.0  2024-05-05

# Lab 4: Read Excel file

In [12]:
orders = pd.read_excel("orders.xlsx", sheet_name="orders")
print(orders.shape)
print(orders.loc[0])

(6, 5)
order_id              101
customer_id             1
product          Keyboard
amount             1200.0
order_date     2024-05-01
Name: 0, dtype: object

# Lab 5: Read JSON file

In [14]:
products = pd.read_json("products.json")
print(products['product_name'])

0    Keyboard
1       Mouse
2     Monitor
Name: product_name, dtype: object

# Lab 6: Inspecting data: head(), tail(), shape(), info(), describe()

In [16]:
customers = pd.read_csv("customers.csv")
print(customers.head())
print(customers.tail())
print(customers.shape)
print(customers.info())
print(customers.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     5 non-null      int64
 1   name            5 non-null      object
 2   city            4 non-null      object
 3   loyalty_points  4 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes
None

# Lab 7: Selecting columns

In [18]:
print(orders[["order_id", "amount"]])

   order_id   amount
0       101   1200.0
1       102    350.5
2       103   8000.0
3       104  55000.0
4       105   1500.0
5       106    900.0

# Lab 8: Filtering rows

In [20]:
filtered_orders = orders[orders["amount"] > 1000]
print(filtered_orders[["order_id", "customer_id","amount"]])

   order_id  customer_id   amount
0       101            1   1200.0
2       103            1   8000.0
3       104            3  55000.0
4       105            2   1500.0

# Lab 9: Handling missing values

In [29]:
print(customers[customers.city.isna()])
print(f"loyalty_points: {customers.loyalty_points.fillna(customers.loyalty_points.mean()).to_list()}")
print(customers.dropna(subset = 'name'))

   customer_id         name city  loyalty_points
4            5  Priya Singh  NaN            50.0
loyalty_points: [120.0, 80.0, 112.5, 200.0, 50.0]

   customer_id         name       city  loyalty_points
0            1  Asha Kapoor       Pune           120.0
1            2  Rahul Mehta     Mumbai            80.0
2            3     Sita Rao  Bengaluru             NaN
3            4     John Doe       Pune           200.0
4            5  Priya Singh        NaN            50.0

# Lab 10: Renaming columns

In [31]:
orders.rename(columns = {"order_id":"id", "customer_id": "cust_id", "order_date":"date"}, inplace = True)
print(orders.loc[0])

id                101
cust_id             1
product      Keyboard
amount         1200.0
date       2024-05-01
Name: 0, dtype: object

# Lab 11: Creating derived columns

In [34]:
orders = pd.read_csv("orders.csv")
orders["amount_with_tax"] = orders["amount"] * 1.18
print(orders[['order_id', "amount", "amount_with_tax"]])

   order_id   amount  amount_with_tax
0       101   1200.0          1416.00
1       102    350.5           413.59
2       103   8000.0          9440.00
3       104  55000.0         64900.00
4       105   1500.0          1770.00
5       106    900.0          1062.00

# Lab 12: Sorting data

In [37]:
print(
    orders.sort_values(by = "amount", ascending = False,)
    [["order_id", "amount"]]
    .head(3)
    )

   order_id   amount
3       104  55000.0
2       103   8000.0
4       105   1500.0

# Lab 13: Grouping and aggregation

In [49]:
df = pd.read_csv("orders.csv")
print(
    df
    .groupby('customer_id')
    .agg(
        total_amount=('amount', 'sum'),
        avg_amount=('amount', 'mean'),
        order_count=('amount', 'count')
    )
    .reset_index()
    .sort_values("total_amount", ascending=False, ignore_index=True)
)

   customer_id  total_amount  avg_amount  order_count
0            3       55000.0    55000.00            1
1            1        9200.0     4600.00            2
2            2        1850.5      925.25            2
3            5         900.0      900.00            1

# Lab 14: Merging DataFrames

In [62]:
customers = pd.read_csv("customers.csv")
orders = pd.read_csv("orders.csv")
merged = orders.merge(customers, on="customer_id")
print(merged[["order_id", "name", "city", "product", "amount"]].head())

   order_id         name       city   product   amount
0       101  Asha Kapoor       Pune  Keyboard   1200.0
1       102  Rahul Mehta     Mumbai     Mouse    350.5
2       103  Asha Kapoor       Pune   Monitor   8000.0
3       104     Sita Rao  Bengaluru    Laptop  55000.0
4       105  Rahul Mehta     Mumbai    Webcam   1500.0

# Lab 15: Exporting output

In [67]:
merged.to_csv("sales_report.csv", index = False)
merged.to_json("sales_report.json", orient = "records")

print(pd.read_csv("sales_report.csv").shape)

(6, 8)

# Final Integrated Lab: Mini ETL — Sales report from raw files

In [88]:
customers = pd.read_csv("customers.csv")
orders = pd.read_csv("orders.csv")
products = pd.read_json("products.json")

df = (
    orders.merge(customers, on="customer_id", how =  'left')
    .merge(products[['product_name', "category"]], left_on="product", right_on="product_name", how = 'left')
    )

df['city'] = df.city.fillna('Unknown')
df['amount_with_tax'] = round(df.amount * 1.18,2)
df['category'] = df.category.fillna('Unknown')

report = (
    df.groupby(['city','category'])
    .agg(
        total_sales=('amount_with_tax','sum'),
        avg_order_value=('amount_with_tax','mean'),
        order_count=('order_id','count'))
    .sort_values(by='total_sales', ascending=False)
    .reset_index()
    )
report.to_csv("city_category_report.csv", index=False)

# Show top rows
print(report)

        city     category  total_sales  avg_order_value  order_count
0  Bengaluru      Unknown     64900.00         64900.00            1
1       Pune     Displays      9440.00          9440.00            1
2     Mumbai      Unknown      1770.00          1770.00            1
3       Pune  Accessories      1416.00          1416.00            1
4    Unknown      Unknown      1062.00          1062.00            1
5     Mumbai  Accessories       413.59           413.59            1